### ISSUE TITLE
how to train on a new dataset?

### ISSUE THREAD

**Issue by asa008** [PramuPerera/DeepOneClass#6]
Sorry to bother you, but how to train on a new dataset? thank you.

**Comment by PramuPerera** [comment]
Hello asa008,

Training on a new dataset can be done by simply replacing the data folders with your own data. I've created two tasks 'abnormal image detection' and 'novelty detection' because their testing protocols are different. In the former, same class is divided into 'normal' and 'abnormal' subsets. Training is done on 'normal' data whereas testing is done with the objective of separating normal from abnormal data. In the latter, it's a 1 vs all problem where the objective is to separate a given class from all other classes. Most real world problems falls under the second category.
